// This file is generated by rust-protobuf 2.28.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `kafka.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_28_0;

#[derive(PartialEq,Clone,Default)]
pub struct ProtoProviderNegotiationKafkaMessage {
    // message fields
    pub procedure: ::protobuf::SingularPtrField<ProtoProcedureKafkaMessage>,
    pub provider_ids: ::protobuf::RepeatedField<::std::string::String>,
    pub negotiated_prices: ::protobuf::RepeatedField<ProtoNegotiatedPriceKafkaMessage>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ProtoProviderNegotiationKafkaMessage {
    fn default() -> &'a ProtoProviderNegotiationKafkaMessage {
        <ProtoProviderNegotiationKafkaMessage as ::protobuf::Message>::default_instance()
    }
}

impl ProtoProviderNegotiationKafkaMessage {
    pub fn new() -> ProtoProviderNegotiationKafkaMessage {
        ::std::default::Default::default()
    }

    // .provider.ProtoProcedureKafkaMessage procedure = 1;


    pub fn get_procedure(&self) -> &ProtoProcedureKafkaMessage {
        self.procedure.as_ref().unwrap_or_else(|| <ProtoProcedureKafkaMessage as ::protobuf::Message>::default_instance())
    }
    pub fn clear_procedure(&mut self) {
        self.procedure.clear();
    }

    pub fn has_procedure(&self) -> bool {
        self.procedure.is_some()
    }

    // Param is passed by value, moved
    pub fn set_procedure(&mut self, v: ProtoProcedureKafkaMessage) {
        self.procedure = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_procedure(&mut self) -> &mut ProtoProcedureKafkaMessage {
        if self.procedure.is_none() {
            self.procedure.set_default();
        }
        self.procedure.as_mut().unwrap()
    }

    // Take field
    pub fn take_procedure(&mut self) -> ProtoProcedureKafkaMessage {
        self.procedure.take().unwrap_or_else(|| ProtoProcedureKafkaMessage::new())
    }

    // repeated string provider_ids = 2;


    pub fn get_provider_ids(&self) -> &[::std::string::String] {
        &self.provider_ids
    }
    pub fn clear_provider_ids(&mut self) {
        self.provider_ids.clear();
    }

    // Param is passed by value, moved
    pub fn set_provider_ids(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.provider_ids = v;
    }

    // Mutable pointer to the field.
    pub fn mut_provider_ids(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.provider_ids
    }

    // Take field
    pub fn take_provider_ids(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.provider_ids, ::protobuf::RepeatedField::new())
    }

    // repeated .provider.ProtoNegotiatedPriceKafkaMessage negotiated_prices = 3;


    pub fn get_negotiated_prices(&self) -> &[ProtoNegotiatedPriceKafkaMessage] {
        &self.negotiated_prices
    }
    pub fn clear_negotiated_prices(&mut self) {
        self.negotiated_prices.clear();
    }

    // Param is passed by value, moved
    pub fn set_negotiated_prices(&mut self, v: ::protobuf::RepeatedField<ProtoNegotiatedPriceKafkaMessage>) {
        self.negotiated_prices = v;
    }

    // Mutable pointer to the field.
    pub fn mut_negotiated_prices(&mut self) -> &mut ::protobuf::RepeatedField<ProtoNegotiatedPriceKafkaMessage> {
        &mut self.negotiated_prices
    }

    // Take field
    pub fn take_negotiated_prices(&mut self) -> ::protobuf::RepeatedField<ProtoNegotiatedPriceKafkaMessage> {
        ::std::mem::replace(&mut self.negotiated_prices, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for ProtoProviderNegotiationKafkaMessage {
    fn is_initialized(&self) -> bool {
        for v in &self.procedure {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.negotiated_prices {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.procedure)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.provider_ids)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.negotiated_prices)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.procedure.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        for value in &self.provider_ids {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        for value in &self.negotiated_prices {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.procedure.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        for v in &self.provider_ids {
            os.write_string(2, &v)?;
        };
        for v in &self.negotiated_prices {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProtoProviderNegotiationKafkaMessage {
        ProtoProviderNegotiationKafkaMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ProtoProcedureKafkaMessage>>(
                "procedure",
                |m: &ProtoProviderNegotiationKafkaMessage| { &m.procedure },
                |m: &mut ProtoProviderNegotiationKafkaMessage| { &mut m.procedure },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "provider_ids",
                |m: &ProtoProviderNegotiationKafkaMessage| { &m.provider_ids },
                |m: &mut ProtoProviderNegotiationKafkaMessage| { &mut m.provider_ids },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ProtoNegotiatedPriceKafkaMessage>>(
                "negotiated_prices",
                |m: &ProtoProviderNegotiationKafkaMessage| { &m.negotiated_prices },
                |m: &mut ProtoProviderNegotiationKafkaMessage| { &mut m.negotiated_prices },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<ProtoProviderNegotiationKafkaMessage>(
                "ProtoProviderNegotiationKafkaMessage",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static ProtoProviderNegotiationKafkaMessage {
        static instance: ::protobuf::rt::LazyV2<ProtoProviderNegotiationKafkaMessage> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ProtoProviderNegotiationKafkaMessage::new)
    }
}

impl ::protobuf::Clear for ProtoProviderNegotiationKafkaMessage {
    fn clear(&mut self) {
        self.procedure.clear();
        self.provider_ids.clear();
        self.negotiated_prices.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProtoProviderNegotiationKafkaMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProtoProviderNegotiationKafkaMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ProtoNegotiatedPriceKafkaMessage {
    // message fields
    pub negotiated_type: ::std::string::String,
    pub negotiated_rate: f64,
    pub expiration_date: ::std::string::String,
    pub service_code: ::protobuf::RepeatedField<::std::string::String>,
    pub billing_class: ::std::string::String,
    pub setting: ::std::string::String,
    pub billing_code_modifier: ::protobuf::RepeatedField<::std::string::String>,
    pub additional_information: ::protobuf::RepeatedField<::std::string::String>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ProtoNegotiatedPriceKafkaMessage {
    fn default() -> &'a ProtoNegotiatedPriceKafkaMessage {
        <ProtoNegotiatedPriceKafkaMessage as ::protobuf::Message>::default_instance()
    }
}

impl ProtoNegotiatedPriceKafkaMessage {
    pub fn new() -> ProtoNegotiatedPriceKafkaMessage {
        ::std::default::Default::default()
    }

    // string negotiated_type = 1;


    pub fn get_negotiated_type(&self) -> &str {
        &self.negotiated_type
    }
    pub fn clear_negotiated_type(&mut self) {
        self.negotiated_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_negotiated_type(&mut self, v: ::std::string::String) {
        self.negotiated_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_negotiated_type(&mut self) -> &mut ::std::string::String {
        &mut self.negotiated_type
    }

    // Take field
    pub fn take_negotiated_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.negotiated_type, ::std::string::String::new())
    }

    // double negotiated_rate = 2;


    pub fn get_negotiated_rate(&self) -> f64 {
        self.negotiated_rate
    }
    pub fn clear_negotiated_rate(&mut self) {
        self.negotiated_rate = 0.;
    }

    // Param is passed by value, moved
    pub fn set_negotiated_rate(&mut self, v: f64) {
        self.negotiated_rate = v;
    }

    // string expiration_date = 3;


    pub fn get_expiration_date(&self) -> &str {
        &self.expiration_date
    }
    pub fn clear_expiration_date(&mut self) {
        self.expiration_date.clear();
    }

    // Param is passed by value, moved
    pub fn set_expiration_date(&mut self, v: ::std::string::String) {
        self.expiration_date = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_expiration_date(&mut self) -> &mut ::std::string::String {
        &mut self.expiration_date
    }

    // Take field
    pub fn take_expiration_date(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.expiration_date, ::std::string::String::new())
    }

    // repeated string service_code = 4;


    pub fn get_service_code(&self) -> &[::std::string::String] {
        &self.service_code
    }
    pub fn clear_service_code(&mut self) {
        self.service_code.clear();
    }

    // Param is passed by value, moved
    pub fn set_service_code(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.service_code = v;
    }

    // Mutable pointer to the field.
    pub fn mut_service_code(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.service_code
    }

    // Take field
    pub fn take_service_code(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.service_code, ::protobuf::RepeatedField::new())
    }

    // string billing_class = 5;


    pub fn get_billing_class(&self) -> &str {
        &self.billing_class
    }
    pub fn clear_billing_class(&mut self) {
        self.billing_class.clear();
    }

    // Param is passed by value, moved
    pub fn set_billing_class(&mut self, v: ::std::string::String) {
        self.billing_class = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_billing_class(&mut self) -> &mut ::std::string::String {
        &mut self.billing_class
    }

    // Take field
    pub fn take_billing_class(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.billing_class, ::std::string::String::new())
    }

    // string setting = 6;


    pub fn get_setting(&self) -> &str {
        &self.setting
    }
    pub fn clear_setting(&mut self) {
        self.setting.clear();
    }

    // Param is passed by value, moved
    pub fn set_setting(&mut self, v: ::std::string::String) {
        self.setting = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_setting(&mut self) -> &mut ::std::string::String {
        &mut self.setting
    }

    // Take field
    pub fn take_setting(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.setting, ::std::string::String::new())
    }

    // repeated string billing_code_modifier = 7;


    pub fn get_billing_code_modifier(&self) -> &[::std::string::String] {
        &self.billing_code_modifier
    }
    pub fn clear_billing_code_modifier(&mut self) {
        self.billing_code_modifier.clear();
    }

    // Param is passed by value, moved
    pub fn set_billing_code_modifier(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.billing_code_modifier = v;
    }

    // Mutable pointer to the field.
    pub fn mut_billing_code_modifier(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.billing_code_modifier
    }

    // Take field
    pub fn take_billing_code_modifier(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.billing_code_modifier, ::protobuf::RepeatedField::new())
    }

    // repeated string additional_information = 8;


    pub fn get_additional_information(&self) -> &[::std::string::String] {
        &self.additional_information
    }
    pub fn clear_additional_information(&mut self) {
        self.additional_information.clear();
    }

    // Param is passed by value, moved
    pub fn set_additional_information(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.additional_information = v;
    }

    // Mutable pointer to the field.
    pub fn mut_additional_information(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.additional_information
    }

    // Take field
    pub fn take_additional_information(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.additional_information, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for ProtoNegotiatedPriceKafkaMessage {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.negotiated_type)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.negotiated_rate = tmp;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.expiration_date)?;
                },
                4 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.service_code)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.billing_class)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.setting)?;
                },
                7 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.billing_code_modifier)?;
                },
                8 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.additional_information)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.negotiated_type.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.negotiated_type);
        }
        if self.negotiated_rate != 0. {
            my_size += 9;
        }
        if !self.expiration_date.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.expiration_date);
        }
        for value in &self.service_code {
            my_size += ::protobuf::rt::string_size(4, &value);
        };
        if !self.billing_class.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.billing_class);
        }
        if !self.setting.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.setting);
        }
        for value in &self.billing_code_modifier {
            my_size += ::protobuf::rt::string_size(7, &value);
        };
        for value in &self.additional_information {
            my_size += ::protobuf::rt::string_size(8, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.negotiated_type.is_empty() {
            os.write_string(1, &self.negotiated_type)?;
        }
        if self.negotiated_rate != 0. {
            os.write_double(2, self.negotiated_rate)?;
        }
        if !self.expiration_date.is_empty() {
            os.write_string(3, &self.expiration_date)?;
        }
        for v in &self.service_code {
            os.write_string(4, &v)?;
        };
        if !self.billing_class.is_empty() {
            os.write_string(5, &self.billing_class)?;
        }
        if !self.setting.is_empty() {
            os.write_string(6, &self.setting)?;
        }
        for v in &self.billing_code_modifier {
            os.write_string(7, &v)?;
        };
        for v in &self.additional_information {
            os.write_string(8, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProtoNegotiatedPriceKafkaMessage {
        ProtoNegotiatedPriceKafkaMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "negotiated_type",
                |m: &ProtoNegotiatedPriceKafkaMessage| { &m.negotiated_type },
                |m: &mut ProtoNegotiatedPriceKafkaMessage| { &mut m.negotiated_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                "negotiated_rate",
                |m: &ProtoNegotiatedPriceKafkaMessage| { &m.negotiated_rate },
                |m: &mut ProtoNegotiatedPriceKafkaMessage| { &mut m.negotiated_rate },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "expiration_date",
                |m: &ProtoNegotiatedPriceKafkaMessage| { &m.expiration_date },
                |m: &mut ProtoNegotiatedPriceKafkaMessage| { &mut m.expiration_date },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "service_code",
                |m: &ProtoNegotiatedPriceKafkaMessage| { &m.service_code },
                |m: &mut ProtoNegotiatedPriceKafkaMessage| { &mut m.service_code },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "billing_class",
                |m: &ProtoNegotiatedPriceKafkaMessage| { &m.billing_class },
                |m: &mut ProtoNegotiatedPriceKafkaMessage| { &mut m.billing_class },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "setting",
                |m: &ProtoNegotiatedPriceKafkaMessage| { &m.setting },
                |m: &mut ProtoNegotiatedPriceKafkaMessage| { &mut m.setting },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "billing_code_modifier",
                |m: &ProtoNegotiatedPriceKafkaMessage| { &m.billing_code_modifier },
                |m: &mut ProtoNegotiatedPriceKafkaMessage| { &mut m.billing_code_modifier },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "additional_information",
                |m: &ProtoNegotiatedPriceKafkaMessage| { &m.additional_information },
                |m: &mut ProtoNegotiatedPriceKafkaMessage| { &mut m.additional_information },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<ProtoNegotiatedPriceKafkaMessage>(
                "ProtoNegotiatedPriceKafkaMessage",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static ProtoNegotiatedPriceKafkaMessage {
        static instance: ::protobuf::rt::LazyV2<ProtoNegotiatedPriceKafkaMessage> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ProtoNegotiatedPriceKafkaMessage::new)
    }
}

impl ::protobuf::Clear for ProtoNegotiatedPriceKafkaMessage {
    fn clear(&mut self) {
        self.negotiated_type.clear();
        self.negotiated_rate = 0.;
        self.expiration_date.clear();
        self.service_code.clear();
        self.billing_class.clear();
        self.setting.clear();
        self.billing_code_modifier.clear();
        self.additional_information.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProtoNegotiatedPriceKafkaMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProtoNegotiatedPriceKafkaMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ProtoProcedureKafkaMessage {
    // message fields
    pub negotiation_arrangement: ::std::string::String,
    pub name: ::std::string::String,
    pub billing_code_type: ::std::string::String,
    pub billing_code_type_version: ::std::string::String,
    pub billing_code: ::std::string::String,
    pub description: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ProtoProcedureKafkaMessage {
    fn default() -> &'a ProtoProcedureKafkaMessage {
        <ProtoProcedureKafkaMessage as ::protobuf::Message>::default_instance()
    }
}

impl ProtoProcedureKafkaMessage {
    pub fn new() -> ProtoProcedureKafkaMessage {
        ::std::default::Default::default()
    }

    // string negotiation_arrangement = 1;


    pub fn get_negotiation_arrangement(&self) -> &str {
        &self.negotiation_arrangement
    }
    pub fn clear_negotiation_arrangement(&mut self) {
        self.negotiation_arrangement.clear();
    }

    // Param is passed by value, moved
    pub fn set_negotiation_arrangement(&mut self, v: ::std::string::String) {
        self.negotiation_arrangement = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_negotiation_arrangement(&mut self) -> &mut ::std::string::String {
        &mut self.negotiation_arrangement
    }

    // Take field
    pub fn take_negotiation_arrangement(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.negotiation_arrangement, ::std::string::String::new())
    }

    // string name = 2;


    pub fn get_name(&self) -> &str {
        &self.name
    }
    pub fn clear_name(&mut self) {
        self.name.clear();
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        &mut self.name
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.name, ::std::string::String::new())
    }

    // string billing_code_type = 3;


    pub fn get_billing_code_type(&self) -> &str {
        &self.billing_code_type
    }
    pub fn clear_billing_code_type(&mut self) {
        self.billing_code_type.clear();
    }

    // Param is passed by value, moved
    pub fn set_billing_code_type(&mut self, v: ::std::string::String) {
        self.billing_code_type = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_billing_code_type(&mut self) -> &mut ::std::string::String {
        &mut self.billing_code_type
    }

    // Take field
    pub fn take_billing_code_type(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.billing_code_type, ::std::string::String::new())
    }

    // string billing_code_type_version = 4;


    pub fn get_billing_code_type_version(&self) -> &str {
        &self.billing_code_type_version
    }
    pub fn clear_billing_code_type_version(&mut self) {
        self.billing_code_type_version.clear();
    }

    // Param is passed by value, moved
    pub fn set_billing_code_type_version(&mut self, v: ::std::string::String) {
        self.billing_code_type_version = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_billing_code_type_version(&mut self) -> &mut ::std::string::String {
        &mut self.billing_code_type_version
    }

    // Take field
    pub fn take_billing_code_type_version(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.billing_code_type_version, ::std::string::String::new())
    }

    // string billing_code = 5;


    pub fn get_billing_code(&self) -> &str {
        &self.billing_code
    }
    pub fn clear_billing_code(&mut self) {
        self.billing_code.clear();
    }

    // Param is passed by value, moved
    pub fn set_billing_code(&mut self, v: ::std::string::String) {
        self.billing_code = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_billing_code(&mut self) -> &mut ::std::string::String {
        &mut self.billing_code
    }

    // Take field
    pub fn take_billing_code(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.billing_code, ::std::string::String::new())
    }

    // string description = 6;


    pub fn get_description(&self) -> &str {
        &self.description
    }
    pub fn clear_description(&mut self) {
        self.description.clear();
    }

    // Param is passed by value, moved
    pub fn set_description(&mut self, v: ::std::string::String) {
        self.description = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_description(&mut self) -> &mut ::std::string::String {
        &mut self.description
    }

    // Take field
    pub fn take_description(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.description, ::std::string::String::new())
    }
}

impl ::protobuf::Message for ProtoProcedureKafkaMessage {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.negotiation_arrangement)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.name)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.billing_code_type)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.billing_code_type_version)?;
                },
                5 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.billing_code)?;
                },
                6 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.description)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.negotiation_arrangement.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.negotiation_arrangement);
        }
        if !self.name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.name);
        }
        if !self.billing_code_type.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.billing_code_type);
        }
        if !self.billing_code_type_version.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.billing_code_type_version);
        }
        if !self.billing_code.is_empty() {
            my_size += ::protobuf::rt::string_size(5, &self.billing_code);
        }
        if !self.description.is_empty() {
            my_size += ::protobuf::rt::string_size(6, &self.description);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.negotiation_arrangement.is_empty() {
            os.write_string(1, &self.negotiation_arrangement)?;
        }
        if !self.name.is_empty() {
            os.write_string(2, &self.name)?;
        }
        if !self.billing_code_type.is_empty() {
            os.write_string(3, &self.billing_code_type)?;
        }
        if !self.billing_code_type_version.is_empty() {
            os.write_string(4, &self.billing_code_type_version)?;
        }
        if !self.billing_code.is_empty() {
            os.write_string(5, &self.billing_code)?;
        }
        if !self.description.is_empty() {
            os.write_string(6, &self.description)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ProtoProcedureKafkaMessage {
        ProtoProcedureKafkaMessage::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "negotiation_arrangement",
                |m: &ProtoProcedureKafkaMessage| { &m.negotiation_arrangement },
                |m: &mut ProtoProcedureKafkaMessage| { &mut m.negotiation_arrangement },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "name",
                |m: &ProtoProcedureKafkaMessage| { &m.name },
                |m: &mut ProtoProcedureKafkaMessage| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "billing_code_type",
                |m: &ProtoProcedureKafkaMessage| { &m.billing_code_type },
                |m: &mut ProtoProcedureKafkaMessage| { &mut m.billing_code_type },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "billing_code_type_version",
                |m: &ProtoProcedureKafkaMessage| { &m.billing_code_type_version },
                |m: &mut ProtoProcedureKafkaMessage| { &mut m.billing_code_type_version },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "billing_code",
                |m: &ProtoProcedureKafkaMessage| { &m.billing_code },
                |m: &mut ProtoProcedureKafkaMessage| { &mut m.billing_code },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "description",
                |m: &ProtoProcedureKafkaMessage| { &m.description },
                |m: &mut ProtoProcedureKafkaMessage| { &mut m.description },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<ProtoProcedureKafkaMessage>(
                "ProtoProcedureKafkaMessage",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static ProtoProcedureKafkaMessage {
        static instance: ::protobuf::rt::LazyV2<ProtoProcedureKafkaMessage> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ProtoProcedureKafkaMessage::new)
    }
}

impl ::protobuf::Clear for ProtoProcedureKafkaMessage {
    fn clear(&mut self) {
        self.negotiation_arrangement.clear();
        self.name.clear();
        self.billing_code_type.clear();
        self.billing_code_type_version.clear();
        self.billing_code.clear();
        self.description.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ProtoProcedureKafkaMessage {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ProtoProcedureKafkaMessage {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0bkafka.proto\x12\x08provider\"\xee\x01\n$ProtoProviderNegotiationKa\
    fkaMessage\x12D\n\tprocedure\x18\x01\x20\x01(\x0b2$.provider.ProtoProced\
    ureKafkaMessageR\tprocedureB\0\x12#\n\x0cprovider_ids\x18\x02\x20\x03(\t\
    R\x0bproviderIdsB\0\x12Y\n\x11negotiated_prices\x18\x03\x20\x03(\x0b2*.p\
    rovider.ProtoNegotiatedPriceKafkaMessageR\x10negotiatedPricesB\0:\0\"\
    \xfc\x02\n\x20ProtoNegotiatedPriceKafkaMessage\x12)\n\x0fnegotiated_type\
    \x18\x01\x20\x01(\tR\x0enegotiatedTypeB\0\x12)\n\x0fnegotiated_rate\x18\
    \x02\x20\x01(\x01R\x0enegotiatedRateB\0\x12)\n\x0fexpiration_date\x18\
    \x03\x20\x01(\tR\x0eexpirationDateB\0\x12#\n\x0cservice_code\x18\x04\x20\
    \x03(\tR\x0bserviceCodeB\0\x12%\n\rbilling_class\x18\x05\x20\x01(\tR\x0c\
    billingClassB\0\x12\x1a\n\x07setting\x18\x06\x20\x01(\tR\x07settingB\0\
    \x124\n\x15billing_code_modifier\x18\x07\x20\x03(\tR\x13billingCodeModif\
    ierB\0\x127\n\x16additional_information\x18\x08\x20\x03(\tR\x15additiona\
    lInformationB\0:\0\"\xa3\x02\n\x1aProtoProcedureKafkaMessage\x129\n\x17n\
    egotiation_arrangement\x18\x01\x20\x01(\tR\x16negotiationArrangementB\0\
    \x12\x14\n\x04name\x18\x02\x20\x01(\tR\x04nameB\0\x12,\n\x11billing_code\
    _type\x18\x03\x20\x01(\tR\x0fbillingCodeTypeB\0\x12;\n\x19billing_code_t\
    ype_version\x18\x04\x20\x01(\tR\x16billingCodeTypeVersionB\0\x12#\n\x0cb\
    illing_code\x18\x05\x20\x01(\tR\x0bbillingCodeB\0\x12\"\n\x0bdescription\
    \x18\x06\x20\x01(\tR\x0bdescriptionB\0:\0B\0b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
